### ISSUE TITLE
Consider `BLNS: &'static [&'static str]`

### ISSUE THREAD

**Issue by huonw** [mcarton/rust-naughty-strings#1]
With a fixed sized array, adding or removing a string is theoretically a breaking change, e.g. a user could write:

``` rust
let x: [&str; 484] = BLNS;
```

and so changing the length would be a breaking change. (That said, I guess this is unlikely to actually happen.)

By instead defining the value as the following the length is no longer part of the type, and so there's no risk at all.

``` rust
pub const BLNS: &'static [&'static str] = &[...];
```

This should also allow writing just `for x in BLNS { ... }` without the `iter()`.

**Comment by mcarton** [comment]
Totally makes sense, I haven't given much thought of that.
Thanks.
