### ISSUE TITLE
Clarify rustdoc failing to escape and report the bug if it's still an issue

### ISSUE THREAD

**Issue by ssokolow** [mcarton/rust-naughty-strings#3]
If `rustdoc` is failing to escape these strings, that's a serious issue and should be reported, but I couldn't find any mention of the BLNS or rust-naughty-strings in the rustdoc issue tracker.

Since I don't know how to reproduce the bug, that means I can't tell if any of the bugs reported were this one specifically.

Please do one of the following:

1. If it's still a problem, either report it or provide enough information for me to reproduce the problem and report it.
2. If it's not still a problem, please either remove the README line and code comment or tone them down to "previous versions of rustdoc that may still be in use".

**Comment by mcarton** [comment]
It's been fixed a long time ago.
I've removed this message.
